source 'https://rubygems.org'
gem 'github-pages', '198', group: :jekyll_plugins

gem 'jekyll'
gem 'activesupport'
gem 'github-pages-health-check'
gem 'html-pipeline'
gem 'jekyll-avatar'
gem 'jekyll-coffeescript'
gem 'jekyll-default-layout'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-github-metadata'
gem 'jekyll-mentions'
gem 'jekyll-optional-front-matter'
gem 'jekyll-paginate'
gem 'jekyll-readme-index'
gem 'jekyll-redirect-from'
gem 'jekyll-relative-links'
gem 'jekyll-sass-converter'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-swiss'
gem 'jekyll-theme-architect'
gem 'jekyll-theme-cayman'
gem 'jekyll-theme-dinky'
gem 'jekyll-theme-hacker'
gem 'jekyll-theme-leap-day'
gem 'jekyll-theme-merlot'
gem 'jekyll-theme-midnight'
gem 'jekyll-theme-minimal'
gem 'jekyll-theme-modernist'
gem 'jekyll-theme-primer'
gem 'jekyll-theme-slate'
gem 'jekyll-theme-tactile'
gem 'jekyll-theme-time-machine'
gem 'jekyll-titles-from-headings'
gem 'jemoji'
gem 'kramdown'
gem 'liquid'
gem 'listen'
gem 'minima'
gem 'nokogiri', '1.10.4'
gem 'rouge'
gem 'ruby'
gem 'safe_yaml'
gem 'sass'
gem 'sassc'
gem 'guard'
gem 'guard-livereload'
gem 'guard-jekyll'

group :development do
  gem 'guard'
end
